autosave scroll to the top of the new section
tuwien-csd/damap-frontend pull request #37
Opened 2022-11-11 15:04 UTC by lpandath

2022-11-14 14:06 UTC, clarascu requested changes

2022-11-14 14:06 UTC, clarascu commented on apps/damap-frontend/src/app/app.module.ts
> +    MatStepperModule,
This should not be needed here.

2022-11-14 14:06 UTC, clarascu commented on libs/damap/src/lib/components/dmp/dmp.component.ts
> +  move(index: number) {
This function doesn't seem to be used, should be save to remove it.

2022-11-16 12:44 UTC, clarascu approved these changes

2022-11-25 08:27 UTC, lpandath commented
@clarascu i re-based with next and running i do not have any problem but Coverage fails in some lines also from before and im not sure why this happens. Maybe you can check that why this is failing? :/

2022-12-12 09:51 UTC, clarascu approved these changes

2022-12-12 10:01 UTC, merged